"""added-process-table

Revision ID: ef52326e7f5b
Revises: b8ff6048e74f
Create Date: 2026-09-21 15:33:38.505224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ef52326e7f5b"
down_revision: Union[str, Sequence[str], None] = "b8ff6048e74f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "process",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "resource_identifier",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "description", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "additional_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "execution_unit", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "deployment_status", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "resource_identifier",
            "version",
            name="unique_constraint_identifier_version",
        ),
    )
    op.create_index(
        "idx_process_title_gin",
        "process",
        ["title"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_process_resource_identifier"),
        "process",
        ["resource_identifier"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_process_resource_identifier"), table_name="process")
    op.drop_index("idx_process_title_gin", table_name="process", postgresql_using="gin")
    op.drop_table("process")
    # ### end Alembic commands ###
