"""add job table

Revision ID: 3558b501bdb8
Revises: ef52326e7f5b
Create Date: 2026-10-01 10:33:31.077071

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3558b501bdb8"
down_revision: Union[str, Sequence[str], None] = "ef52326e7f5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "ACCEPTED", "RUNNING", "SUCCESSFUL", "FAILED", "DISMISSED", name="jobstatus"
    ).create(op.get_bind())
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "resource_identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACCEPTED",
                "RUNNING",
                "SUCCESSFUL",
                "FAILED",
                "DISMISSED",
                name="jobstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("response_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "additional_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column(
            "processing_entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("exception", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "callback_uris", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["process_id"], ["process.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_resource_identifier"), "job", ["resource_identifier"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_resource_identifier"), table_name="job")
    op.drop_table("job")
    sa.Enum(
        "ACCEPTED", "RUNNING", "SUCCESSFUL", "FAILED", "DISMISSED", name="jobstatus"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
