class PottoException(Exception): ...


class ResourceNotFoundError(PottoException): ...


class CannotCreateResourceError(PottoException): ...


class CannotUpdateResourceError(PottoException): ...


class CannotDeleteResourceError(PottoException): ...


class CannotChangeResourceOwnerException(PottoException): ...


class CannotModifyResourceAccess(PottoException): ...


class UserNotFoundException(PottoException): ...


class DeploymentFailedException(PottoException): ...


class DeploymentAlreadyInProgressError(PottoException): ...


class ProcessExecutionUnitNotSupportedError(PottoException): ...


class PottoCannotSetAdminScopeException(PottoException): ...


class PottoCannotSetScopesException(PottoException): ...


class PottoCannotChangeCollectionOwnerException(PottoException): ...


class PottoCannotModifyCollectionAccessException(PottoException): ...


class PottoCannotEditCollectionException(PottoException): ...


class PottoCannotCreateCollectionException(PottoException): ...


class PottoCannotDeleteCollectionException(PottoException): ...


class PottoCannotEditServerMetadataException(PottoException): ...


class PottoCannotCreateUserException(PottoException): ...


class PottoCannotViewUserException(PottoException): ...


class PottoCannotEditUserException(PottoException): ...


class PottoCannotDeleteUserException(PottoException): ...


class PottoBadRequestException(PottoException): ...


class PottoNotFoundException(PottoException): ...


class PottoCollectionNotFoundException(PottoNotFoundException): ...


class PottoCollectionItemNotFoundException(PottoNotFoundException): ...


class CapabilityNotSupported(PottoException): ...


class MissingConfigurationError(PottoException): ...
