name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

env:
  COLUMNS: 120

jobs:
  run_ci:
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-24.04
    env:
      ARTIFACT_NAME: "python-package"
      POTTO__BIND_HOST: "0.0.0.0"
      POTTO__BIND_PORT: "3001"
      POTTO__DATABASE_DSN: "postgresql+psycopg://potto:pottopass@localhost:55432/potto"
    steps:

      - name: "Grab code"
        uses: actions/checkout@v6.0.2

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Install code with dev-related dependencies"
        run: uv sync --locked --all-groups

      - name: "Run ruff formatter"
        run: uv run ruff format --check

      - name: "Run ruff linter"
        run: uv run ruff check

      - name: "Run ty"
        run: uv run ty check

      - name: "Stand up compose stack for testing"
        run: |
          docker compose --file docker/compose.ci.yaml up --detach --wait

      - name: "Initialize potto database"
        run: |
          uv run potto db upgrade

      - name: "Export OpenAPI schema document"
        run: uv run potto export-openapi --output potto_openapi_ci.json

      - name: "Lint OpenAPI schema with spectral"
        run: |
          npm install --global @stoplight/spectral-cli@6.15.0
          spectral lint potto_openapi_ci.json \
          --ruleset spectral/spectral.yaml \
          --fail-severity info \
          --format github-actions

      - name: "Run integration tests"
        env:
          POTTO__TEST_DATABASE_DSN: "postgresql+psycopg://potto:pottopass@localhost:55433/potto_test"
          POTTO__DEBUG: "true"
        run: uv run pytest -m integration

      - name: "bootstrap potto database with data for OGC CITE testing"
        run: |
          echo "12345678" | uv run potto user create cite-admin --password-stdin --scope admin
          uv run potto cite-testing bootstrap-ogc-api-features-1

      - name: "Launch potto server for OGC CITE testing"
        env:
          POTTO__PUBLIC_URL: "http://host.docker.internal:3001"
          POTTO__USE_OAS30_FIXES: "true"
        run: |
          nohup uv run potto run-server > /dev/null 2>&1 &
          echo $! > potto-server.pid
          sleep 1
          if ps --pid $(cat potto-server.pid) > /dev/null; then
              echo "potto server is up and running with PID $(cat potto-server.pid)"
          else
              echo "potto server failed to start"
              exit 1
          fi

      - name: "Run OGC CITE tests"
        env:
          PUBLIC_URL: "http://host.docker.internal:3001"
        uses: OSGEO/ogc-cite-runner@v0.3.2
        with:
          test_suite_identifier: ogcapi-features-1.0
          test_session_arguments: >-
            iut=${PUBLIC_URL}/api/
            noofcollections=-1

      - name: "Shut down potto server for OGC CITE testing"
        if: always()
        run: |
          if [ -f potto-server.pid ]; then
              echo "Shutting down potto server with PID $(cat potto-server.pid)..."
              kill $(cat potto-server.pid)  || true
              rm potto-server.pid
          fi

      - name: "Stand down compose stack"
        run: |
          docker compose --file docker/compose.ci.yaml down

      - name: "Build Python package"
        run: uv build

      - name: "Upload built package as artifact"
        id: upload_package_artifact
        uses: actions/upload-artifact@v7.0.1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: "${{ env.ARTIFACT_NAME }}"
          path: dist/
          retention-days: 2
